In [15]:
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [16]:
drinks = pd.read_csv("http://bit.ly/drinksbycountry")
drinks.head(200)

,country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol,continent
0,Afghanistan,0,0,0,0.0,Asia
1,Albania,89,132,54,4.9,Europe
2,Algeria,25,0,14,0.7,Africa
3,Andorra,245,138,312,12.4,Europe
4,Angola,217,57,45,5.9,Africa
5,Antigua & Barbuda,102,128,45,4.9,North America
6,Argentina,193,25,221,8.3,South America
7,Armenia,21,179,11,3.8,Europe
8,Australia,261,72,212,10.4,Oceania
9,Austria,279,75,191,9.7,Europe
10,Azerbaijan,21,46,5,1.3,Europe
11,Bahamas,122,176,51,6.3,North America
12,Bahrain,42,63,7,2.0,Asia
13,Bangladesh,0,0,0,0.0,Asia
14,Barbados,143,173,36,6.3,North America
15,Belarus,142,373,42,14.4,Europe
16,Belgium,295,84,212,10.5,Europe
17,Belize,263,114,8,6.8,North America
18,Benin,34,4,13,1.1,Africa
19,Bhutan,23,0,0,0.4,Asia
20,Bolivia,167,41,8,3.8,South America
21,Bosnia-Herzegovina,76,173,8,4.6,Europe
22,Botswana,173,35,35,5.4,Africa
23,Brazil,245,145,16,7.2,South America
24,Brunei,31,2,1,0.6,Asia
25,Bulgaria,231,252,94,10.3,Europe
26,Burkina Faso,25,7,7,4.3,Africa
27,Burundi,88,0,0,6.3,Africa
28,Cote d'Ivoire,37,1,7,4.0,Africa
29,Cabo Verde,144,56,16,4.0,Africa
...,...,...,...,...,...,...
163,Suriname,128,178,7,5.6,South America
164,Swaziland,90,2,2,4.7,Africa
165,Sweden,152,60,186,7.2,Europe
166,Switzerland,185,100,280,10.2,Europe
167,Syria,5,35,16,1.0,Asia
168,Tajikistan,2,15,0,0.3,Asia
169,Thailand,99,258,1,6.4,Asia
170,Macedonia,106,27,86,3.9,Europe
171,Timor-Leste,1,1,4,0.1,Asia
172,Togo,36,2,19,1.3,Africa
173,Tonga,36,21,5,1.1,Oceania
174,Trinidad & Tobago,197,156,7,6.4,North America
175,Tunisia,51,3,20,1.3,Africa
176,Turkey,51,22,7,1.4,Asia
177,Turkmenistan,19,71,32,2.2,Asia
178,Tuvalu,6,41,9,1.0,Oceania
179,Uganda,45,9,0,8.3,Africa
180,Ukraine,206,237,45,8.9,Europe
181,United Arab Emirates,16,135,5,2.8,Asia
182,United Kingdom,219,126,195,10.4,Europe
183,Tanzania,36,6,1,5.7,Africa
184,USA,249,158,84,8.7,North America
185,Uruguay,115,35,220,6.6,South America
186,Uzbekistan,25,101,8,2.4,Asia
187,Vanuatu,21,18,11,0.9,Oceania
188,Venezuela,333,100,3,7.7,South America
189,Vietnam,111,2,1,2.0,Asia
190,Yemen,6,0,0,0.1,Asia
191,Zambia,32,19,4,2.5,Africa
192,Zimbabwe,64,18,4,4.7,Africa

In [17]:
drinks['country']
drinks.groupby('country').sum()

,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol
country,,,,
Afghanistan,0,0,0,0.0
Albania,89,132,54,4.9
Algeria,25,0,14,0.7
Andorra,245,138,312,12.4
Angola,217,57,45,5.9
Antigua & Barbuda,102,128,45,4.9
Argentina,193,25,221,8.3
Armenia,21,179,11,3.8
Australia,261,72,212,10.4
Austria,279,75,191,9.7
Azerbaijan,21,46,5,1.3
Bahamas,122,176,51,6.3
Bahrain,42,63,7,2.0
Bangladesh,0,0,0,0.0
Barbados,143,173,36,6.3
Belarus,142,373,42,14.4
Belgium,295,84,212,10.5
Belize,263,114,8,6.8
Benin,34,4,13,1.1
Bhutan,23,0,0,0.4
Bolivia,167,41,8,3.8
Bosnia-Herzegovina,76,173,8,4.6
Botswana,173,35,35,5.4
Brazil,245,145,16,7.2
Brunei,31,2,1,0.6
Bulgaria,231,252,94,10.3
Burkina Faso,25,7,7,4.3
Burundi,88,0,0,6.3
Cabo Verde,144,56,16,4.0
Cambodia,57,65,1,2.2
...,...,...,...,...
Sudan,8,13,0,1.7
Suriname,128,178,7,5.6
Swaziland,90,2,2,4.7
Sweden,152,60,186,7.2
Switzerland,185,100,280,10.2
Syria,5,35,16,1.0
Tajikistan,2,15,0,0.3
Tanzania,36,6,1,5.7
Thailand,99,258,1,6.4
Timor-Leste,1,1,4,0.1
Togo,36,2,19,1.3
Tonga,36,21,5,1.1
Trinidad & Tobago,197,156,7,6.4
Tunisia,51,3,20,1.3
Turkey,51,22,7,1.4
Turkmenistan,19,71,32,2.2
Tuvalu,6,41,9,1.0
USA,249,158,84,8.7
Uganda,45,9,0,8.3
Ukraine,206,237,45,8.9
United Arab Emirates,16,135,5,2.8
United Kingdom,219,126,195,10.4
Uruguay,115,35,220,6.6
Uzbekistan,25,101,8,2.4
Vanuatu,21,18,11,0.9
Venezuela,333,100,3,7.7
Vietnam,111,2,1,2.0
Yemen,6,0,0,0.1
Zambia,32,19,4,2.5
Zimbabwe,64,18,4,4.7

In [18]:
type(drinks['country'])

pandas.core.series.Series

In [19]:
type(drinks)

pandas.core.frame.DataFrame

In [20]:
drinks[['country', 'beer_servings', 'continent']]

                  country  beer_servings      continent
0             Afghanistan              0           Asia
1                 Albania             89         Europe
2                 Algeria             25         Africa
3                 Andorra            245         Europe
4                  Angola            217         Africa
5       Antigua & Barbuda            102  North America
6               Argentina            193  South America
7                 Armenia             21         Europe
8               Australia            261        Oceania
9                 Austria            279         Europe
10             Azerbaijan             21         Europe
11                Bahamas            122  North America
12                Bahrain             42           Asia
13             Bangladesh              0           Asia
14               Barbados            143  North America
15                Belarus            142         Europe
16                Belgium            295         Europe
17                 Belize            263  North America
18                  Benin             34         Africa
19                 Bhutan             23           Asia
20                Bolivia            167  South America
21     Bosnia-Herzegovina             76         Europe
22               Botswana            173         Africa
23                 Brazil            245  South America
24                 Brunei             31           Asia
25               Bulgaria            231         Europe
26           Burkina Faso             25         Africa
27                Burundi             88         Africa
28          Cote d'Ivoire             37         Africa
29             Cabo Verde            144         Africa
..                    ...            ...            ...
163              Suriname            128  South America
164             Swaziland             90         Africa
165                Sweden            152         Europe
166           Switzerland            185         Europe
167                 Syria              5           Asia
168            Tajikistan              2           Asia
169              Thailand             99           Asia
170             Macedonia            106         Europe
171           Timor-Leste              1           Asia
172                  Togo             36         Africa
173                 Tonga             36        Oceania
174     Trinidad & Tobago            197  North America
175               Tunisia             51         Africa
176                Turkey             51           Asia
177          Turkmenistan             19           Asia
178                Tuvalu              6        Oceania
179                Uganda             45         Africa
180               Ukraine            206         Europe
181  United Arab Emirates             16           Asia
182        United Kingdom            219         Europe
183              Tanzania             36         Africa
184                   USA            249  North America
185               Uruguay            115  South America
186            Uzbekistan             25           Asia
187               Vanuatu             21        Oceania
188             Venezuela            333  South America
189               Vietnam            111           Asia
190                 Yemen              6           Asia
191                Zambia             32         Africa
192              Zimbabwe             64         Africa

[193 rows x 3 columns]

In [32]:
drinks = ["beer_servings"]#.groupby('continent').sum()

In [33]:
type(drinks)

list

In [34]:
drinks[['country','beer_servings','continent']]

TypeError: list indices must be integers or slices, not list

In [24]:
type(drinks['country'])

TypeError: list indices must be integers or slices, not str

In [25]:
drinks[drinks.continent=='Asia']

AttributeError: 'list' object has no attribute 'continent'

In [26]:
beer = drinks[['country','beer_servings','continent']]
beer.head(50)

TypeError: list indices must be integers or slices, not list

In [27]:
drinks.groupby("continent").plot(kind='bar')

AttributeError: 'list' object has no attribute 'groupby'

In [28]:
drinks.groupby("continent").mean().plot(kind='bar')

AttributeError: 'list' object has no attribute 'groupby'

In [29]:
beer.groupby("continent").head()

NameError: name 'beer' is not defined

In [30]:
beer_Asia = beer[beer.continent=="Asia"].beer_servings #groupby("continent")
beer_NorthAmerica = beer[beer.continent=="North America"].beer_servings
beer_Europe = beer[beer.continent=="Europe"].beer_servings
beer_Africa = beer[beer.continent=="Africa"].beer_servings
beer_Oceania = beer[beer.continent=="Oceania"].beer_servings
beer_SouthAmerica = beer[beer.continent=="South America"].beer_servings
fig = plt.figure()
fig.suptitle('LAS350A Lab 6', fontsize=14, fontweight='bold')
ax = fig.add_subplot(111)
ax.boxplot((beer_Asia, beer_NorthAmerica, beer_Europe, beer_Africa, beer_SouthAmerica, beer_Oceania))

NameError: name 'beer' is not defined